FROM node:8 as builder

COPY remotecowork.ui /ui
WORKDIR /ui


FROM nginx

COPY --from=builder /ui/dist /usr/share/nginx/html
COPY remotecowork.ui/docker/jimber.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]